version: '3'

services:
  outbound:
    environment:
      - MHS_OUTBOUND_ROUTING_LOOKUP_METHOD=SDS_API
      - MHS_SDS_API_URL=http://sds-api-mock
      - MHS_SDS_API_KEY=none

  route:
    deploy:
      replicas: 0

  redis:
    deploy:
      replicas: 0

  sds-api-mock:
    build: ./dockers/sds-api-mock
    ports:
      - "80"
    command:
      - -global-response-templating