version: '3'
services:
  fakespine:
    logging:
      driver: awslogs
      options:
        awslogs-region: "eu-west-2"
        awslogs-group: "/aws/ec2/fake-spine-ec2-instance"
        awslogs-create-group: "true"
    ports:
      - "443:443"
      - "80:80"
    