version: '3'

services:
  outbound:
    environment:
      - MHS_OUTBOUND_ROUTING_LOOKUP_METHOD=SDS_API
      - MHS_SDS_API_URL=https://internal-dev.api.service.nhs.uk/spine-directory/FHIR/R4
      - MHS_SDS_API_KEY=none

  route:
    deploy:
      replicas: 0

  redis:
    deploy:
      replicas: 0
