apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: inbound
  name: inbound
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  - name: "80"
    port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 172.28.65.240
  selector:
    io.kompose.service: inbound
status:
  loadBalancer: {}
