#!/usr/bin/env bash

#GLOBAL VARS
export AWS_ACCESS_KEY_ID="test"
export AWS_SECRET_ACCESS_KEY="test"
export MHS_STATE_TABLE_NAME="random"
export MHS_DB_ENDPOINT_URL="http://dynamodb:8000"

#RABBITMQ VARS
export RABBITMQ_PORT_1="15672"
export RABBITMQ_PORT_2="5672"
export RABBITMQ_HOSTNAME="localhost"

#MHS OUTBOUND VARS
export MHS_OUTBOUND_PORT="80"

#MHS INBOUND VARS
export MHS_INBOUND_QUEUE_BROKERS="amqp://rabbitmq:5672"
export MHS_SECRET_INBOUND_QUEUE_USERNAME="guest"
export MHS_SECRET_INBOUND_QUEUE_PASSWORD="guest"
export MHS_INBOUND_HEALTHCHECK_SERVER_PORT="8082"

#MHS ROUTE VARS
export MHS_ROUTE_PORT="8080"
export MHS_SDS_REDIS_CACHE_HOST="redis"
export MHS_SDS_REDIS_DISABLE_TLS="True"

export MHS_CLOUD_REGION="eu-west-2"