----=_MIME-Boundary
Content-Id: <ebXMLHeader@spine.nhs.uk>
Content-Type: text/xml; charset=UTF-8
Content-Transfer-Encoding: 8bit

{{ebxml}}
----=_MIME-Boundary
Content-Id: <C614484E-4B10-499A-9ACD-5D645CFACF61@spine.nhs.uk>
Content-Type: application/xml
Content-Transfer-Encoding: 8bit

<hl7:MCCI_IN010000UK13 xmlns:hl7="urn:hl7-org:v3"/>
----=_MIME-Boundary
Content-Id: <8F1D7DE1-02AB-48D7-A797-A947B09F347F@spine.nhs.uk>
Content-Type: text/plain
Content-Transfer-Encoding: base64

jj2Ln886YL4rjojQ7NLcmwWWu9CQMLmgevxThRBIMv501+zRfFB9vFM39baF+uzabvV718ZWbd2nO916
7phnuAzC57RJyzsN+9ootsm+Q3YLYb9z54riB7z0QbbdbF4br8xN7ZZN3yt2+l2GeY5Z5NL0E0urYFft
0Gs1rg2ZbRHWlkP+8k4F1s/AD0pTu/kCn7VSG0e64rNbTluj132qP+cLJONT8Z5G5MB4bxr8sVA7elMz
wOpWYlT9z7FfOu3maYNCqDzA9Ipeza1O5whzpVIRuI16ebPTd66VbpuqTwRIGrw25k81JdbB8t2Hib/S
cx0vVv8WWPW/Bf8CszTdwWLwb+O/2u1DyfkYAAA=
----=_MIME-Boundary--
