apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: outbound
  name: outbound
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: outbound
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: outbound
    spec:
      containers:
      - env:
        - name: AWS_ACCESS_KEY_ID
          value: test
        - name: AWS_SECRET_ACCESS_KEY
          value: test
        - name: MAX_RESYNC_RETRIES
          value: "20"
        - name: MHS_DB_ENDPOINT_URL
          value: http://dynamodb:8000
        - name: MHS_FORWARD_RELIABLE_ENDPOINT_URL
          value: https://192.168.128.11/reliablemessaging/forwardreliable
        - name: MHS_LOG_LEVEL
          value: NOTSET
        - name: MHS_OUTBOUND_VALIDATE_CERTIFICATE
          value: "False"
        - name: MHS_RESYNC_INTERVAL
          value: "1"
        - name: MHS_SPINE_ORG_CODE
          value: YES
        - name: MHS_SPINE_REQUEST_MAX_SIZE
          value: NOTSET
        - name: MHS_SPINE_ROUTE_LOOKUP_URL
          value: http://route
        - name: MHS_STATE_TABLE_NAME
          value: mhs_state
        - name: MHS_SYNC_ASYNC_STATE_TABLE_NAME
          value: sync_async_state
        - name: SERVICE_PORTS
          value: "80"
        image: nhsdev/nia-mhs-outbound:0.0.2
        imagePullPolicy: ""
        name: outbound
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
