apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: route
  name: route
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: route
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: route
    spec:
      containers:
      - env:
        - name: MHS_DISABLE_SDS_TLS
          value: "False"
        - name: MHS_LOG_LEVEL
          value: DEBUG
        - name: MHS_SDS_REDIS_CACHE_HOST
          value: mhs-adaptor-cache.redis.cache.windows.net
        - name: MHS_SDS_REDIS_CACHE_PORT
          value: "6379"
        - name: MHS_SDS_REDIS_DISABLE_TLS
          value: "True"
        - name: MHS_SDS_SEARCH_BASE
          value: ou=services,o=nhs
        - name: MHS_SDS_URL
          value: ldaps://ldap.nis1.national.ncrs.nhs.uk
        - name: MHS_SECRET_CLIENT_CERT
          valueFrom:
            secretKeyRef:
              name: mhs-client-cert
              key: tls.crt
        - name: MHS_SECRET_CLIENT_KEY	
          valueFrom:
            secretKeyRef:
              name: mhs-client-cert
              key: tls.key
        - name: MHS_SECRET_CA_CERTS
          valueFrom:
            secretKeyRef:
              name: mhs-ca-certs
              key: ca-certs
        image: nhsdev/nia-mhs-route:1.0.0
        imagePullPolicy: ""
        name: route
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      serviceAccountName: ""
      volumes: null
status: {}
