@startuml Vaccine Passport Context Diagram
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

title Vaccine Passport Context Diagram

System_Ext(app, "NHS App", "")
System_Ext(login, "NHS Login", "")
System(vacc, "Vaccination Gateway", "Orchestrates generation of vaccine passport certificates")
System_Ext(data, "Vaccination Records", "FHIR Data Access Layer")
System_Ext(notify, "Gov.uk Notify", "Distribute certificate via email/print")

Rel(app, login, "Login using", "OIDC")
Rel(app, vacc, "Requests a certificate generation", "NHS Number, patient demographics")
Rel(vacc, data, "Fetch vaccination data from", "FHIR data")
Rel(vacc, notify, "Send certificate to", "PDF and metadata")
@enduml